create extension if not exists pgcrypto;
create type public.user_role as enum ('student','admin');
create type public.exam_status as enum ('draft','published','archived');
create type public.exam_kind as enum ('classification','regression','mixed');
create type public.question_type as enum ('single_choice','integer','decimal','percentage','unit_value','text');
create type public.grading_type as enum ('exact','rounded','absolute_tolerance','relative_tolerance','multiple_answers');
create type public.attempt_status as enum ('in_progress','submitted','expired','graded');

create table public.profiles(id uuid primary key references auth.users on delete cascade,birth_date date not null,role public.user_role not null default 'student',display_name text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(birth_date between date '1900-01-01' and current_date));
create table public.user_consents(id bigint generated always as identity primary key,user_id uuid not null references public.profiles on delete cascade,consent_type text not null check(consent_type in('terms','privacy','marketing')),version text not null,accepted boolean not null,accepted_at timestamptz not null default now(),unique(user_id,consent_type,version));
create table public.exams(id uuid primary key default gen_random_uuid(),slug text not null unique,title text not null,description text,kind public.exam_kind not null,status public.exam_status not null default 'draft',duration_minutes smallint not null default 60 check(duration_minutes between 1 and 300),passing_score numeric(5,2) not null default 80 check(passing_score between 0 and 100),total_score numeric(6,2) not null default 100 check(total_score>0),fixed_order boolean not null default true,published_at timestamptz,created_by uuid references public.profiles on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.exam_sections(id uuid primary key default gen_random_uuid(),exam_id uuid not null references public.exams on delete cascade,code text not null,title text not null,description text,max_score numeric(6,2) not null check(max_score>0),sort_order smallint not null default 0,unique(exam_id,code));
create table public.questions(id uuid primary key default gen_random_uuid(),exam_id uuid not null references public.exams on delete cascade,section_id uuid not null references public.exam_sections on delete restrict,number smallint not null check(number>0),type public.question_type not null,prompt text not null,instructions text,score numeric(6,2) not null check(score>0),difficulty smallint not null default 2 check(difficulty between 1 and 5),competency_tags text[] not null default '{}',prerequisite_question_id uuid references public.questions on delete set null,answer_format_hint text,explanation text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(exam_id,number));
create table public.question_choices(id uuid primary key default gen_random_uuid(),question_id uuid not null references public.questions on delete cascade,label text not null,content text not null,sort_order smallint not null default 0,unique(question_id,label));
create table public.answer_keys(question_id uuid primary key references public.questions on delete cascade,grading_type public.grading_type not null,correct_choice_id uuid references public.question_choices on delete restrict,correct_value text,accepted_values text[] not null default '{}',decimal_places smallint check(decimal_places between 0 and 12),tolerance numeric(20,10) check(tolerance is null or tolerance>=0),case_sensitive boolean not null default false,updated_at timestamptz not null default now(),check(correct_choice_id is not null or correct_value is not null or cardinality(accepted_values)>0));
create table public.exam_assets(id uuid primary key default gen_random_uuid(),exam_id uuid not null references public.exams on delete cascade,asset_type text not null check(asset_type in('dataset','guide','image','attachment')),title text not null,bucket_id text not null,object_path text not null,is_downloadable boolean not null default true,sort_order smallint not null default 0,created_at timestamptz not null default now(),unique(bucket_id,object_path));
create table public.attempts(id uuid primary key default gen_random_uuid(),exam_id uuid not null references public.exams on delete restrict,user_id uuid not null references public.profiles on delete cascade,status public.attempt_status not null default 'in_progress',started_at timestamptz not null default now(),expires_at timestamptz not null,submitted_at timestamptz,graded_at timestamptz,total_score numeric(6,2),correct_count smallint,answered_count smallint not null default 0,passed boolean,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(expires_at>started_at));
create unique index attempts_one_active_per_exam on public.attempts(user_id,exam_id) where status='in_progress';
create table public.attempt_answers(id uuid primary key default gen_random_uuid(),attempt_id uuid not null references public.attempts on delete cascade,question_id uuid not null references public.questions on delete restrict,selected_choice_id uuid references public.question_choices on delete restrict,answer_text text,is_flagged boolean not null default false,is_correct boolean,awarded_score numeric(6,2),answered_at timestamptz not null default now(),graded_at timestamptz,unique(attempt_id,question_id),check(selected_choice_id is not null or answer_text is not null));
create table public.section_results(id uuid primary key default gen_random_uuid(),attempt_id uuid not null references public.attempts on delete cascade,section_id uuid not null references public.exam_sections on delete restrict,earned_score numeric(6,2) not null default 0,max_score numeric(6,2) not null,correct_count smallint not null default 0,question_count smallint not null default 0,percentage numeric(5,2) not null default 0,unique(attempt_id,section_id));
create table public.diagnostic_rules(id uuid primary key default gen_random_uuid(),section_code text,competency_tag text,min_percentage numeric(5,2) not null,max_percentage numeric(5,2) not null,level text not null check(level in('foundation','weak','developing','strong')),comment text not null,recommendation text,priority smallint not null default 0,is_active boolean not null default true,check(min_percentage between 0 and 100 and max_percentage between min_percentage and 100));

create index on public.user_consents(user_id);create index on public.exam_sections(exam_id);create index on public.questions(exam_id);create index on public.questions(section_id);create index on public.question_choices(question_id);create index on public.exam_assets(exam_id);create index on public.attempts(user_id);create index on public.attempt_answers(attempt_id);create index on public.section_results(attempt_id);

create schema if not exists private;revoke all on schema private from public,anon,authenticated;
create function private.is_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=(select auth.uid()) and role='admin')$$;
create function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end$$;
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at();create trigger exams_updated before update on public.exams for each row execute function public.set_updated_at();create trigger questions_updated before update on public.questions for each row execute function public.set_updated_at();create trigger attempts_updated before update on public.attempts for each row execute function public.set_updated_at();
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,birth_date) values(new.id,(new.raw_user_meta_data->>'birth_date')::date);return new;exception when others then raise exception 'A valid birth_date is required';end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;alter table public.user_consents enable row level security;alter table public.exams enable row level security;alter table public.exam_sections enable row level security;alter table public.questions enable row level security;alter table public.question_choices enable row level security;alter table public.answer_keys enable row level security;alter table public.exam_assets enable row level security;alter table public.attempts enable row level security;alter table public.attempt_answers enable row level security;alter table public.section_results enable row level security;alter table public.diagnostic_rules enable row level security;

create policy "own profile read" on public.profiles for select to authenticated using((select auth.uid())=id);create policy "own profile update" on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id and role='student');create policy "admin profiles" on public.profiles for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "own consents read" on public.user_consents for select to authenticated using((select auth.uid())=user_id);create policy "own consents insert" on public.user_consents for insert to authenticated with check((select auth.uid())=user_id);create policy "admin consents" on public.user_consents for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "published exams read" on public.exams for select to anon,authenticated using(status='published' or (select private.is_admin()));create policy "admin exams" on public.exams for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "published sections read" on public.exam_sections for select to anon,authenticated using(exists(select 1 from public.exams e where e.id=exam_id and e.status='published') or (select private.is_admin()));create policy "admin sections" on public.exam_sections for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "published questions read" on public.questions for select to authenticated using((is_active and exists(select 1 from public.exams e where e.id=exam_id and e.status='published')) or (select private.is_admin()));create policy "admin questions" on public.questions for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "published choices read" on public.question_choices for select to authenticated using(exists(select 1 from public.questions q join public.exams e on e.id=q.exam_id where q.id=question_id and q.is_active and e.status='published') or (select private.is_admin()));create policy "admin choices" on public.question_choices for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "admin answer keys" on public.answer_keys for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "published assets read" on public.exam_assets for select to authenticated using(exists(select 1 from public.exams e where e.id=exam_id and e.status='published') or (select private.is_admin()));create policy "admin assets" on public.exam_assets for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "own attempts read" on public.attempts for select to authenticated using((select auth.uid())=user_id);create policy "own attempts insert" on public.attempts for insert to authenticated with check((select auth.uid())=user_id and status='in_progress' and exists(select 1 from public.exams e where e.id=exam_id and e.status='published'));create policy "admin attempts" on public.attempts for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "own answers read" on public.attempt_answers for select to authenticated using(exists(select 1 from public.attempts a where a.id=attempt_id and a.user_id=(select auth.uid())));create policy "own active answers insert" on public.attempt_answers for insert to authenticated with check(exists(select 1 from public.attempts a where a.id=attempt_id and a.user_id=(select auth.uid()) and a.status='in_progress' and now()<a.expires_at));create policy "own active answers update" on public.attempt_answers for update to authenticated using(exists(select 1 from public.attempts a where a.id=attempt_id and a.user_id=(select auth.uid()) and a.status='in_progress' and now()<a.expires_at)) with check(exists(select 1 from public.attempts a where a.id=attempt_id and a.user_id=(select auth.uid()) and a.status='in_progress' and now()<a.expires_at));create policy "admin answers" on public.attempt_answers for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "own results read" on public.section_results for select to authenticated using(exists(select 1 from public.attempts a where a.id=attempt_id and a.user_id=(select auth.uid())));create policy "admin results" on public.section_results for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));
create policy "diagnostics read" on public.diagnostic_rules for select to authenticated using(is_active or (select private.is_admin()));create policy "admin diagnostics" on public.diagnostic_rules for all to authenticated using((select private.is_admin())) with check((select private.is_admin()));

insert into storage.buckets(id,name,public,file_size_limit) values('exam-datasets','exam-datasets',false,52428800),('exam-assets','exam-assets',false,10485760),('exam-guides','exam-guides',false,52428800) on conflict(id) do nothing;
create policy "exam files read" on storage.objects for select to authenticated using(bucket_id in('exam-datasets','exam-assets','exam-guides'));create policy "admin files insert" on storage.objects for insert to authenticated with check(bucket_id in('exam-datasets','exam-assets','exam-guides') and (select private.is_admin()));create policy "admin files update" on storage.objects for update to authenticated using(bucket_id in('exam-datasets','exam-assets','exam-guides') and (select private.is_admin())) with check(bucket_id in('exam-datasets','exam-assets','exam-guides') and (select private.is_admin()));create policy "admin files delete" on storage.objects for delete to authenticated using(bucket_id in('exam-datasets','exam-assets','exam-guides') and (select private.is_admin()));

insert into public.diagnostic_rules(min_percentage,max_percentage,level,comment,recommendation,priority) values(0,39.99,'foundation','기초 개념과 AIDU 메뉴 흐름을 먼저 익혀야 합니다.','기본 예제를 따라 한 뒤 쉬운 문항부터 다시 풀어보세요.',40),(40,59.99,'weak','핵심 개념은 일부 이해했지만 결과 해석과 적용이 부족합니다.','틀린 세부역량의 해설을 확인하고 같은 유형을 반복 연습하세요.',30),(60,79.99,'developing','기본기는 갖추었지만 복합 조건 문항에서 보완이 필요합니다.','조건과 출력값을 체크리스트로 확인하는 연습을 권장합니다.',20),(80,100,'strong','해당 영역을 안정적으로 이해하고 있습니다.','실전 시간 관리와 고난도 문항에 집중하세요.',10);
